PENG-2414 implement the whole functionality required to initiate the project
omnivector-solutions/vantage-jobs-catalog pull request #1
Opened 2024-10-17 20:49 UTC by matheushent

This PR implements the whole logic defined in the task with little modifications.

For specific details, check out the acceptance criteria on [ClickUp](https://app.clickup.com/t/18022949/PENG-2414).

2024-10-22 19:10 UTC, dusktreader requested changes
Awesome work, here! I left some comments for you.

2024-10-22 19:10 UTC, dusktreader commented on cfd-openfoam-motorbike/job-script.sh
> +fi
Is there any way we can just get the needed files and provide them as supporting files? It sucks to need to clone the repository as a part of the job script.

2024-10-22 19:10 UTC, dusktreader commented on cfd-openfoam-motorbike/metadata.yaml
> +icon-url: ""
We should use this for the icon-url: https://upload.wikimedia.org/wikipedia/commons/4/48/OpenFOAM_logo.svg

2024-10-22 19:10 UTC, dusktreader commented on cfd-openfoam-motorbike/metadata.yaml
> +supporting-files: []
If we aren't including any, we should leave this out.

2024-10-22 19:10 UTC, dusktreader commented on index.html
Can this go in the infra folder? It's weird in the root folder without any clues as to what it's used for.

2024-10-23 14:34 UTC, matheushent commented on README.md
> +* **Apptainer Image URI**: The URI of the Apptainer image containing the necessary software and dependencies for the job.
you're right, I will fix it

2024-10-23 14:43 UTC, matheushent commented on README.md
> +icon-url: ""
I'm not sure about this. I think it is better to have all `metadata.yaml` files with the same keys and some of them empty than having non-standardized files

2024-10-23 14:43 UTC, matheushent commented on README.md
> +supporting-files: []
same comment: https://github.com/omnivector-solutions/vantage-jobs-catalog/pull/1#discussion_r1812938861

2024-10-23 14:57 UTC, matheushent commented on builder/main.py
> +from __future__ import annotations
that's correct, thank you

2024-10-23 15:14 UTC, matheushent commented on builder/subapps/helpers.py
> +"""Core module for apptainer related operations."""
you right, I will fix it

2024-10-23 15:18 UTC, matheushent commented on builder/subapps/helpers.py
> +        logger.debug(f"Loading metadata.yaml from {job_script_path}")
most likely it is a leftover

2024-10-23 15:19 UTC, matheushent commented on builder/subapps/helpers.py
> +    render_json(metadata.model_dump(mode="json"))
that's correct. I actually saw this behaviour in other function and forgot to modify this one

2024-10-23 15:24 UTC, matheushent commented on cfd-openfoam-motorbike/job-script.sh
> +fi
well, there a way. We could just add all files under this directory as supporting files: https://github.com/OpenFOAM/OpenFOAM-11/tree/master/tutorials/incompressibleFluid/motorBike

2024-10-23 15:25 UTC, matheushent commented on cfd-openfoam-motorbike/metadata.yaml
> +icon-url: ""
this is not a squared logo as we talked in private with Andre. I guess we need to assign him the task of creating those logos, then we store on our public s3

2024-10-23 15:27 UTC, matheushent commented on cfd-openfoam-motorbike/metadata.yaml
> +supporting-files: []
check my comment here: https://github.com/omnivector-solutions/vantage-jobs-catalog/pull/1#discussion_r1812938861

2024-10-23 15:27 UTC, matheushent commented on README.md
> +icon-url: ""
I'd be fine removing empty values if we have some sort of api spec file, like a openapi.yaml definition.

2024-10-23 15:28 UTC, matheushent commented on index.html
actually it can be removed

2024-10-23 15:30 UTC, matheushent commented
@dusktreader some of your suggestions have been applied in [20c62dc](https://github.com/omnivector-solutions/vantage-jobs-catalog/pull/1/commits/20c62dc7ff596b094a6df3c99ec250f4bba7dea6). Some I left for discussion.

2024-10-23 17:45 UTC, dusktreader commented on README.md
> +icon-url: ""
I would be fine with adding a spec file for both the metadata.yaml file and the catalog.yaml file.

2024-10-23 17:45 UTC, dusktreader commented on README.md
> +icon-url: ""
I still think it's better to leave out fields with no values rather than put a blank in there.

2024-10-23 17:48 UTC, dusktreader commented on README.md
> +* **s3:PutObjectAcl**
You can actually use an alert and it renders nicely on github: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts

2024-10-23 17:54 UTC, dusktreader commented on cfd-openfoam-motorbike/job-script.sh
> +fi
Oh, god....that' no good. I guess leave the clone as-is.

2024-10-23 17:54 UTC, dusktreader commented on cfd-openfoam-motorbike/metadata.yaml
> +icon-url: ""
His designs include non-squared logos, though. I think we will support it.

2024-10-23 17:58 UTC, matheushent commented on README.md
> +* **s3:PutObjectAcl**
I couldn't verify that locally because it is GitHub specific, not Markdown specific

2024-10-23 17:59 UTC, matheushent commented on README.md
> +New jobs can be added to the repository respecting the following acceptance criteria:
can you name a reason? My point is that it is better to have all sub projects with the same pattern of file. Even if the spec is a good alternative, it would require some work to develop it since I'd need to implement some sort of checker, otherwise it's useless.

2024-10-23 20:04 UTC, dusktreader commented on README.md
> +* **s3:PutObjectAcl**
OK. Though, people will primarily be viewing this document from github.

2024-10-23 20:22 UTC, matheushent commented on cfd-openfoam-motorbike/metadata.yaml
> +icon-url: ""
I know. I mean the link you suggested isn't a square logo.

2024-10-24 04:03 UTC, matheushent commented on README.md
> +icon-url: ""
can you name a reason? In my opinion, it's better to leave the empty fields due to two things:
1. lack of automated way for checking the `metadata.yaml`
2. standardization to avoid [1]

2024-10-24 15:39 UTC, matheushent commented on README.md
> +icon-url: ""
I just noticed that the [JobScriptMetadata](https://github.com/omnivector-solutions/vantage-jobs-catalog/blob/matheushent/PENG-2414--init-project/builder/schemas.py#L8) model lints entries in the `metadata.yaml`. I will modify the readme

2024-10-24 15:43 UTC, matheushent commented on README.md
> +icon-url: ""
done in [145bd80](https://github.com/omnivector-solutions/vantage-jobs-catalog/pull/1/commits/145bd804b44e392fd4e31c1a3635c1791c553a8c)

2024-10-24 15:43 UTC, matheushent commented on README.md
> +supporting-files: []
done in [145bd80](https://github.com/omnivector-solutions/vantage-jobs-catalog/pull/1/commits/145bd804b44e392fd4e31c1a3635c1791c553a8c)

2024-10-24 16:31 UTC, dusktreader commented on cfd-openfoam-motorbike/metadata.yaml
> +icon-url: ""
Yes, I realize that. I am saying that his designs seem to allow for non-square logos. So, we should include this for now. Later, we can use a squared version of the logo.

2024-10-24 17:06 UTC, matheushent commented on cfd-openfoam-motorbike/metadata.yaml
> +icon-url: ""
done in [f79fb11](https://github.com/omnivector-solutions/vantage-jobs-catalog/pull/1/commits/f79fb11e8d6543312b3df7759d5b0cd1d89b31cb)

2024-10-24 17:34 UTC, dusktreader approved these changes

2024-10-24 21:12 UTC, merged